Feature/overview columns
Progressus-io/postnl-for-woocommerce pull request #105
Opened 2023-06-21 07:35 UTC by Abdalsalaam

### Description

On the order overview page, I added 2 new columns Delivery Date & Shipping options

### Steps to Test

1. Create an order with delivery date.
2. Create the label for this order with some shipping options.
3. Check the orders list.

<img width="1267" alt="image" src="https://github.com/Progressus-io/postnl-for-woocommerce/assets/19236737/8e910f0a-a8ab-4f71-a927-e41c6e919cc4">

2023-06-22 09:22 UTC, iyut requested changes
Overall the code looks good. I just left some comment about small code cosmetic

2023-06-22 09:22 UTC, iyut commented on src/Order/OrdersList.php
> +		}
```suggestion
		if ( empty( $order_id ) ) {
		     return;
		}
	
		if ( 'postnl_shipping_options' === $column ) {
			$backend_data = $this->get_backend_data( $order_id );

			echo Utils::generate_shipping_options_html( $backend_data );
		}
```

2023-06-22 09:22 UTC, iyut commented on src/Order/OrdersList.php
> +		}
Let's try to not use **nested if** as much as possible.

2023-06-22 09:22 UTC, iyut commented on src/Order/OrdersList.php
> +		}
```suggestion
		if ( empty( $order_id ) ) {
		return;
		}

		if ( 'postnl_delivery_date' === $column ) {
			$order = wc_get_order( $order_id );

			if ( ! is_a( $order, 'WC_Order' ) ) {
				return;
			}

			$delivery_info = $this->get_order_frontend_info( $order, 'delivery_day_date' );

			echo Utils::generate_delivery_date_html( $delivery_info );
		}
```

2023-06-22 09:22 UTC, iyut commented on src/Utils.php
> +				'packets'               => __( 'Packets', 'postnl-for-woocommerce' ),
```suggestion
				'id_check'              => esc_html__( 'ID Check', 'postnl-for-woocommerce' ),
				'insured_shipping'      => esc_html__( 'Insured Shipping', 'postnl-for-woocommerce' ),
				'return_no_answer'      => esc_html__( 'Return if no answer', 'postnl-for-woocommerce' ),
				'signature_on_delivery' => esc_html__( 'Signature on Delivery', 'postnl-for-woocommerce' ),
				'only_home_address'     => esc_html__( 'Only Home Address', 'postnl-for-woocommerce' ),
				'letterbox'             => esc_html__( 'Letterbox', 'postnl-for-woocommerce' ),
				'packets'               => esc_html__( 'Packets', 'postnl-for-woocommerce' ),
```

Let's make it more secure

2023-06-22 11:45 UTC, Abdalsalaam commented
> Overall the code looks good. I just left some comment about small code cosmetic

Thank you @iyut , I made some changes

2023-06-23 08:12 UTC, iyut approved these changes
Looks good!

2023-06-27 15:42 UTC, merged