Letterbox implementation
Progressus-io/postnl-for-woocommerce pull request #160
Opened 2024-05-20 15:19 UTC by OlfatProgressus

2024-05-20 23:13 UTC, Abdalsalaam requested changes
Nice work @OlfatProgressus 
I still didn't test the plugin functionality but I left some comments

2024-05-20 23:13 UTC, Abdalsalaam commented on src/Utils.php
> +	public static function is_eligible_auto_letterbox( $order ) {
I suggest to create a **single responsibility** function for checking the order and another for checking the cart


```suggestion
	public static function is_order_eligible_auto_letterbox( $order ) {
```

```suggestion
	public static function is_cart_eligible_auto_letterbox( $cart ) {
```

2024-05-20 23:13 UTC, Abdalsalaam commented on src/Utils.php
> +		}
```suggestion
		if ( 'BE' !== wc_get_base_location()['country'] ) {
			return false;
		}
```
[When doing logical comparisons involving variables, always put the variable on the right side and put constants, literals, or function calls on the left side](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#yoda-conditions)

2024-05-20 23:13 UTC, Abdalsalaam commented on src/Utils.php
> +		return ( $total_ratio_letterbox_item <= 1 ) ? true : false;
```suggestion
		return $total_ratio_letterbox_item <= 1;
```

2024-05-21 10:30 UTC, OlfatProgressus commented on languages/postnlnew.po
This file is the new version of translations

2024-05-23 09:30 UTC, Abdalsalaam commented
Can you please add the change log ( fixes/features ) ? @olfat123

2024-06-10 11:37 UTC, merged