Create Drop point and delivery day blocks
Progressus-io/postnl-for-woocommerce pull request #191
Opened 2024-10-21 15:17 UTC by sal4sup

- Created Drop Point Block
- Created Delivery Day Block
- Added shipping and billing address fields
- Handled data returned from the API
- Stored order values on the backend

2024-10-25 17:23 UTC, sal4sup commented
I encountered the following console error:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'registerBlockType')
```

The error is resolved when I move the `Blocks_Integration` and `Extend_Block_Core` files to the main plugin directory. Here's the relevant code snippet:

```php
/**
 * Function to register blocks after WooCommerce Blocks are loaded.
 */
function shipping_workshop_register_blocks() {
    require_once __DIR__ . '/Blocks_Integration1.php';

    // Register the blocks integration
    add_action( 'woocommerce_blocks_checkout_block_registration', function( $integration_registry ) {
        $integration_registry->register( new \Blocks_Integration1() );
    } );
}

add_action( 'woocommerce_blocks_loaded', __NAMESPACE__ . '\\shipping_workshop_register_blocks' );
require_once __DIR__ . '/Extend_Block_Core1.php';

new \Extend_Block_Core();
```

I suspect this issue might be related to PSR-4 and namespacing. Any insights or advice?

2024-11-11 02:27 UTC, iyut commented
I got this fatal error when I tried to activate the plugin : 
<img width="792" alt="Screenshot 2024-11-11 at 09 25 58" src="https://github.com/user-attachments/assets/fda6a36f-cdcf-45ff-9e3b-aaddb0d21c56">

I have runned : `composer i` `nvm i` `npm i` `npm run build`

2024-12-03 03:06 UTC, iyut requested changes
I think we can clean the unneeded files on this PR.

2024-12-03 03:06 UTC, iyut commented on src/Checkout_Blocks/js/postnl-delivery-day/block.json
Do we need this? CMIIW, but I think `block.json` only needed for the main js file such as index.js or frontend.js.

2024-12-03 03:06 UTC, iyut commented on src/Checkout_Blocks/js/postnl-dropoff-points/block.json
Do we need this? CMIIW, but I think `block.json` only needed for the main js file such as index.js or frontend.js.

2025-03-17 08:46 UTC, merged